### ISSUE TITLE
allow new-style formatting strings?

### ISSUE THREAD

**Issue by nsheff** [databio/logmuse#6]
right now we're using [old style](https://realpython.com/python-string-formatting/#1-old-style-string-formatting-operator) string formatting, but the logging Formatter can accept new-style:

https://docs.python.org/3/library/logging.html#logging.Formatter

Should we make this possible here: 
https://github.com/databio/logmuse/blob/a84d5b4166877682bfca11abbcf4027b41bfb563/logmuse/est.py#L233

**Comment by vreuter** [comment]
I'm not sure what you mean; are you suggesting a change in implementation, or in usage? Right now throughout various project we mix usage of `%` and `.format` in the way in which we build messages, but it sounds like you're suggesting an implementation here. Is that so that we constrain our usages to a single style?

**Comment by nsheff** [comment]
`logging.Formatter` accepts a 'style' arg, but this is not passed through in our code. I'm suggesting allowing a user to use new-style Formatters with logmuse.
